name: ci

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup Nodejs 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      -
        name: Install Dependencies
        run: yarn install
      -
        name: Run test
        run: yarn test

